import numpy as np
import MDAnalysis as mda
import lammps2omm as lmm
import sys
import random
import string

# Check filename if it is solvent vs. system
filename = sys.argv[1]
lmpdata_file = filename+".data"
pdb_file = filename+".pdb"

# Load LAMMPS data file as a Universe object
# Topology of the system is a bit screwed up but the new topology
# for the PDB files will be rewritten later. 
Natoms = len(u.atoms)
u.add_TopologyAttr('record_types',['HETATM']*Natoms)

# Open a solvent.data manually and read topology
lmm.grab_lmpdata_attr(lmpdata_file)

## Delete topology attributes
u.delete_bonds(u.bonds)
u.delete_dihedrals(u.dihedrals)
u.delete_impropers(u.impropers)
u.delete_angles(u.angles)

# Add new topology attributes to remove warnings
u.add_TopologyAttr('elements',lmm.lmp_allels)
u.add_TopologyAttr('chainIDs',['A']*Natoms)
u.add_TopologyAttr('altLocs',['']*Natoms)
u.add_TopologyAttr('icodes',['']*len(u.residues))
u.add_TopologyAttr('tempfactors',[0]*Natoms)
u.add_TopologyAttr('occupancies',[1.0]*Natoms)

# Open the corresponding PDB file (generated by packmol)
lmm.grab_pdbdata_attr(pdb_file)
u.add_TopologyAttr('names',lmm.pdb_names)
u.add_TopologyAttr('resnames',lmm.pdb_resname_mol)

lmm.write_forcefield(u,filename)
lmm.write_pdbfile(u,filename)
